version: "3.8"

services:
  mongo:
    image: mongo
    volumes:
      - ./.mongo:/data/db:delegated
    ports:
      - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:3.9.20-management'
    ports:
      - '5672:5672'
      - '15672:15672'
