services:
  Mooc.Users.Repository:
    class: ../../../../Contexts/Mooc/Users/Infrastructure/MongoUserRepository
    arguments: [ '@Shared.ConnectionManager', '@Shared.MongoCriteriaConverter' ]

  Mooc.Users.CreateUser:
    class: ../../../../Contexts/Mooc/Users/Application/CreateUser
    arguments: [ '@Mooc.Users.Repository', '@Shared.EventBus' ]

  Mooc.Users.DeleteUser:
    class: ../../../../Contexts/Mooc/Users/Application/DeleteUser
    arguments: [ '@Mooc.Users.Repository' ]

  Mooc.Users.FindUsersByCriteria:
    class: ../../../../Contexts/Mooc/Users/Application/FindUsersByCriteria
    arguments: [ '@Mooc.Users.Repository' ]
